platform :ios, :deployment_target => "9.0"

def swift_pods
    use_frameworks!
    pod 'SnapKit'
end

def testing_pods
    use_frameworks!
    pod 'Nimble'
end


target 'DogFeatureApp' do
  swift_pods
 end

target 'DogFeatureAppTests' do
    swift_pods
    testing_pods
end

target 'DogFeature' do
xcodeproj '../DogFeature'
inherit! :search_paths
  swift_pods
 end
 
 workspace 'DogFeatureApp.xcworkspace'